# Generated by Django 4.2.3 on 2023-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roberts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roberts',
            name='robert_cate_name',
            field=models.CharField(max_length=250),
        ),
    ]
