# Generated by Django 4.2.3 on 2023-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_roberts_robert_cate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roberts',
            name='manufacture_name',
            field=models.CharField(max_length=250),
        ),
    ]
